### PR TITLE
More AUR stuff

### PR DESCRIPTION
**Pull request by ThatOneCalculator**
Big thing is adding the bin package

### CODE REVIEW

**Comment by ThatOneCalculator** [comment]
Drafting until 0.2.2beta is out

**Comment by ThatOneCalculator** [comment]
Requesting review from @vaxerski

**Comment by vaxerski** [comment]
shouldnt we make it depend on polkit too? im tired of people saying shit doesnt work on their plain arch installs without polkit

**Comment by ThatOneCalculator** [comment]
@vaxerski re-requesting review

**Comment by vaxerski** [comment]
just noticed. You removed `wlroots-git`, but you didn't add wlroots-git deps. It won't build on clean systems. Wlroots will fail.

**Comment by ThatOneCalculator** [comment]
Ah. Lemme correct that.

**Comment by ThatOneCalculator** [comment]
@vaxerski Done, and pushed to the AUR

**Comment by vaxerski** [comment]
I'll trust you with those depends, lmao

lgtm

**Comment by ThatOneCalculator** [comment]
as for the deps, i tested it and everything workey

**Pull request merged**
