### PR TITLE
Nix: use meson for builds

### PR DESCRIPTION
**Pull request by fufexan**
#### Describe your PR, what does it fix/add?
- Use meson in Nix builds.
- Update nixpkgs and wlroots
- Change wlroots url to Kainoa's mirror

#### Is there anything you want to mention? (unchecked code, possible bugs, found problems, breaking compatibility, etc.)

Depends on #205

#### Is it ready for merging, or does it need work?

Pretty sure it's ready for merging as soon as #205 is merged.

Requesting reviews from @viperML @Tanish2002 @Narice

### CODE REVIEW

**Comment by vaxerski** [comment]
cool. If the first PR gets finished I will merge this

**Comment by viperML** [comment]
If the versions are going to get written into `meson.build`, it could be possible to parse it to get the version in the flake automatically

**Comment by fufexan** [comment]
Indeed, haven't thought about it.

**Comment by fufexan** [comment]
@viperML now the update workflow will also update the flake version.

**Comment by sp1ritCS** [comment]
@fufexan no idea how robust that regex for the version update workflow is, you might want to consider running `meson introspect <builddir> --projectinfo | jq -r .version`. But that'd require configuring a builddir first. No idea it thats better :9

**Comment by fufexan** [comment]
@sp1ritCS thanks. I didn't know about `meson introspect`. Can it also set the version, or does it only get it? Even if it is a solution, I'll still have to search for another way of changing the flake.nix version.

@viperML any idea?

**Comment by fufexan** [comment]
pinging the Nix guys for a last check @viperML @Tanish2002 @Narice

**Pull request merged**
