### PR TITLE
Change features section in readme

### PR DESCRIPTION
**Pull request by ThatOneCalculator**
Fixes typo, adds drawing tablet

### CODE REVIEW

**Comment by ThatOneCalculator** [comment]
> drawing tablets arent supported doe, my simple quick fix didnt work lmao

oh damn, just keep this open then until you do lmaoo

**Comment by vaxerski** [comment]
hope to do it tomorrow but i got into this one cool anime which reminds me of my miserable life by portraying happy people who are only a bit younger than me enjoying their fulfilling journey while i am stuck alone in my room developing a fucking display server so idk if i'll find time

**Comment by ThatOneCalculator** [comment]
whats the name of thbe anime

**Comment by vaxerski** [comment]
冴えないヘロイネの育て方

**Comment by MartiniMoe** [comment]
Theres a typo in the added feature in the list :eyes:

**Comment by ThatOneCalculator** [comment]
Wait where, I'm incredibly gay and cannot read or write

**Comment by ThatOneCalculator** [comment]
Holy shit how did I manage to misspell support :finnadie:

**Comment by vaxerski** [comment]
mousehole

**Comment by ThatOneCalculator** [comment]
@vaxerski merge this or else

**Comment by vaxerski** [comment]
no

**Pull request merged**
