### PR TITLE
move, set active, recalc, anim on monitor connected

### PR DESCRIPTION
**Pull request by Vagahbond**
Describe your PR, what does it fix/add?
Fixes wonky tile placement when plugging in new monitor

Is there anything you want to mention? (unchecked code, possible bugs, found problems, breaking compatibility, etc.)
Vaxry made this I just copied from discord

Is it ready for merging, or does it need work?
I believe it's ready, you tell me

### CODE REVIEW

**Comment by fufexan** [comment]
Formatting affected the entire file. Can you perhaps only format the relevant part?

**Comment by Vagahbond** [comment]
ooooops my bad it's automated I didnt notice

**Comment by fufexan** [comment]
LGTM. Could you squash the commits?

**Comment by Vagahbond** [comment]
Why not using squash and merge functionnality from gh ?

**Comment by fufexan** [comment]
Idk. Haven't seen vaxry use that in previous PRs.

**Comment by vaxerski** [comment]
because idek how to do that from the fiucking mobile app

**Comment by vaxerski** [comment]
ok don

**Pull request merged**
