### PR TITLE
Documentation Rework

### PR DESCRIPTION
**Pull request by ElectronicsArchiver**
Please check the previews:
- [`README.md`][Readme]
- [`docs/Install.md`][Install]
- [`docs/Contribute.md`][Contribute]

### Questions / Suggestions

- Consider enabling discussions, for exchanges 
  not relating to specific / active issues

- Is there a specific reason you are using
  GitHub Wiki pages?

  *If not, consider using the `/docs/` folder*
  *instead, as wiki pages are horrible to*
  *contribute to, don't have subfolders,*
  *can't have relative links to repo*
  *resources,..*

- Move the removed TODO 
  points to **[Projects]**

  *Todo Points:*
```
 - Input Methods (wlr_input_method_v2)
 - Animations (some new, like workspace)
 - Fix electron rendering issues
 - Optimization
 - Fix weird scroll on XWayland (if possible)
 - Become sane
 - STABILITY
 - More config options for tweakers
 - Improve hyprctl
```

### Changes

- General formatting / spacing
- Converted raw links into link references
- Linked badges
- Moved install into dedicated file
- Linked thanks
- Added quicklinks
- Removed todo -> projects

[Contribute]: https://github.com/ElectronicsArchiver/Hyprland/blob/main/docs/Contribute.md
[Readme]: https://github.com/ElectronicsArchiver/Hyprland
[Install]: https://github.com/ElectronicsArchiver/Hyprland/blob/main/docs/Install.md
[Projects]: https://github.com/vaxerski/Hyprland/projects?type=beta

### CODE REVIEW

**Comment by vaxerski** [comment]
Discussions - sure.

Why wiki pages? Idk, cuz they are easy to get to, I guess.


A lot of the changes are nice, but I personally hate the material badges, the traditional Github ones are better, imo.

I'll fix some spelling mistakes and stuff tomorrow, I noticed at least three, but it's midnight

**Comment by ElectronicsArchiver** [comment]
Well the for-the-badge style is more readable 
with it's bigger font and greater padding.

Sure, see you tomorrow~

**Comment by vaxerski** [comment]
okay so I changed what I wanted to change in the MDs, now:

- discussions have been opened.

- Regarding the wiki - imho it's here to stay. It's visible, easy to navigate, etc.

You can link to other parts of the repo from the wiki - you just have to use the absolute link and not relative links.

You can't contribute easily, yes, but isn't that what the wiki should be like? It's not the code. Especially when I've now enabled discussions, I will probably make a discussion in a while  called "Wiki change requests" and people can request fixes/updates there.

Regarding the MDs: Avoid large, unnecessary spacing, avoid useless bold/italics. I've removed a bunch of those.

Regarding projects: I can't see those. I've never used projects and I don't think they work with PRs.

**Comment by ElectronicsArchiver** [comment]
> You can't contribute easily, yes, but isn't that what the wiki should be like?

Huh?

> Avoid large, unnecessary spacing, avoid useless bold/italics

You make me sad, x3

> I can't see those.

5th item in the tab bar on your repository page..

>  I've never used projects

A reason to try using them~

>  I don't think they work with PRs.

What about them doesn't work with PRs?


*I guess I'm happy that at least some*
*parts of the PR got accepted x3*

I'd like to fix the syntax at the top of the
README before you merge though~

**Comment by vaxerski** [comment]
> What about them doesn't work with PRs?
Projects are empty. Both in your repo and in mine.

> I'd like to fix the syntax at the top of the
README before you merge though~
feel free

**Comment by ElectronicsArchiver** [comment]
> Projects are empty. Both in your repo and in mine.

Well you would have to create one, either the new type or the old.
Old ones on the repo, new ones on your profile.

> feel free

sure

**Comment by vaxerski** [comment]
lgtm, thanks

**Pull request merged**
