### PR TITLE
Added reference to GIT-aur version of hyprland

### PR DESCRIPTION
**Pull request by sandervankasteel**
### Describe your PR, what does it fix/add?

Adds reference to the AUR-git version of hyprland.

### Is there anything you want to mention? (unchecked code, possible bugs, found problems, breaking compatibility, etc.)

No

### Is it ready for merging, or does it need work?
Does not need any work

### CODE REVIEW

**Comment by vaxerski** [comment]
thanks, improved the styling a bit and added more info.

**Comment by sandervankasteel** [comment]
> thanks, improved the styling a bit and added more info.

You are welcome! 

PS. I am also the person maintaining the AUR package :)

**Comment by vaxerski** [comment]
thanks for the package!

**Comment by vaxerski** [comment]
I hope you tested it, in Hypr the package was broken at first because PKGBUILD sets some weird-ass flags that would produce a broken Hypr executable that wouldn't work.

**Pull request merged**
