### PR TITLE
Change wlroots submodule url to github mirror

### LINKED ISSUE #211: Make GitHub mirror of wlroots on Freedesktop
Given the instability/downtime of the freedesktop gitlab server, a mirror should be made on GitHub and used as the submodule.

### PR DESCRIPTION
**Pull request by ThatOneCalculator**
Closes #211

### CODE REVIEW

**Comment by vaxerski** [comment]
wallahi wallah if u try to do something funky with your mirror amma make my own

**Comment by ThatOneCalculator** [comment]
:kiss:

**Comment by vaxerski** [comment]
wallahi wallah if u try to do something funky with your mirror amma make my own

also commit hashes are preserved right?

**Comment by ThatOneCalculator** [comment]
yea they preserved it's literally a mirror

**Comment by ThatOneCalculator** [comment]
why don't you mirror some bitches

**Pull request merged**
